[package]
name = "solver"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
itertools = "0"
inferno = "0"
clap = {version = "3", features = ["derive"]}
once_cell = "1"